Repository bcgov/nr-get-token, pull requests merged in 2019-08, with the labels that each got.

#76 Add Patroni Postgresql DB support
  Jenkinsfile
  Jenkinsfile.cicd
  backend/.sequelizerc
  backend/.snyk
  backend/app.js
  backend/config/custom-environment-variables.json
  backend/config/database.js
  backend/config/default.json
  backend/config/production.json
  backend/config/test.json
  backend/package-lock.json
  backend/package.json
  backend/src/controllers/acronyms.js
  backend/src/controllers/index.js
  backend/src/controllers/users.js
  backend/src/migrations/20190729000000-initialize-database.js
  backend/src/models/acronym.js
  backend/src/models/index.js
  backend/src/models/lifecycle.js
  backend/src/models/lifecyclehistory.js
  backend/src/models/user.js
  backend/src/models/useracronym.js
  backend/src/routes/auth.js
  frontend/Caddyfile
  openshift/backend.bc.yaml
  openshift/backend.dc.yaml
  openshift/frontend-static.bc.yaml
  openshift/frontend-static.dc.yaml
  openshift/frontend.bc.yaml
  openshift/patroni-ephemeral.dc.yaml
  openshift/patroni.dc.yaml
  openshift/patroni.secret.yaml
Labels: enhancement

#77 Reduce PVC size from 5 to 2gb
  openshift/patroni.dc.yaml
Labels: bug

#78 Ensure Patroni is up first before frontend and backend may proceed
  Jenkinsfile
  Jenkinsfile.cicd
Labels: bug

#79 Add audit logging business logic support
  backend/README.md
  backend/app.js
  backend/package-lock.json
  backend/package.json
  backend/src/components/appConfig.js
  backend/src/components/auth.js
  backend/src/controllers/acronyms.js
  backend/src/controllers/index.js
  backend/src/controllers/users.js
  backend/src/migrations/20190729000000-initialize-database.js
  backend/src/models/lifecycle.js
  backend/src/models/lifecyclehistory.js
  backend/src/routes/auth.js
  backend/src/routes/v1/appConfigForm.js
  backend/src/services/acronym.js
  backend/src/services/index.js
  backend/src/services/lifecycle.js
  backend/src/services/user.js
  backend/tests/unit/components/appConfig.spec.js
  backend/tests/unit/components/auth.spec.js
Labels: enhancement

#80 Remove tools directory content
  README.md
  backend/README.md
  backend/src/services/acronym.js
  openshift/README.md
  tools/README.md
  tools/jenkins/Jenkinsfile
  tools/jenkins/docker/Dockerfile
  tools/jenkins/docker/contrib/jenkins/configuration/init.groovy.d/003-create-jobs.groovy
  tools/jenkins/docker/contrib/jenkins/configuration/init.groovy.d/100-jenkins-config-set-admin-address.groovy
  tools/jenkins/docker/contrib/jenkins/configuration/org.jenkinsci.plugins.workflow.libs.GlobalLibraries.xml
  tools/jenkins/docker/contrib/jenkins/configuration/scriptApproval.xml
  tools/jenkins/openshift/build-master.yaml
  tools/jenkins/openshift/build-slave.yaml
  tools/jenkins/openshift/deploy-master.yaml
  tools/jenkins/openshift/deploy-slave.yaml
  tools/jenkins/openshift/jobs-config.yaml
  tools/jenkins/openshift/ns-config.yaml
  tools/jenkins/openshift/secrets.yaml
Labels: bug, documentation

#81 Set local cached images to periodically schedule updates from sources
  openshift/backend.bc.yaml
  openshift/frontend-static.bc.yaml
  openshift/frontend.bc.yaml
Labels: enhancement

#82 KeyCloak Realm Service Clients
  backend/config/custom-environment-variables.json
  backend/config/default.json
  backend/config/test.json
  backend/package-lock.json
  backend/package.json
  backend/src/components/keyCloakServiceClientMgr.js
  backend/src/components/realmAdminSvc.js
  backend/src/docs/v1.api-spec.yaml
  backend/src/routes/v1.js
  backend/src/routes/v1/kcClientForm.js
  backend/tests/unit/components/keyCloakServiceClientMgr.spec.js
  backend/tests/unit/components/realmAdminSvc.spec.js
  backend/tests/unit/routes/v1.spec.js
  openshift/README.md
  openshift/backend.dc.yaml
Labels: documentation, enhancement
