Repository bcgov/nr-get-token, pull requests merged in 2020-04, with the labels that each got.

#159 API access step4
  app/frontend/src/assets/scss/style.scss
  app/frontend/src/components/apiAccess/ApiAccess.vue
  app/frontend/src/components/apiAccess/Step2.vue
  app/frontend/src/components/apiAccess/Step3.vue
  app/frontend/src/components/apiAccess/Step4.vue
  app/frontend/src/views/Application.vue
  openshift/commonPipeline.groovy
Labels: enhancement

#158 Make sure PRs have seed data
  app/README.md
  app/config/database.js
  app/frontend/src/components/admin/ApiTester.vue
  app/frontend/src/components/admin/Clients.vue
  app/frontend/src/components/admin/HealthDialog.vue
  app/frontend/src/components/admin/JWTDialog.vue
  app/frontend/src/components/base/BaseAuthButton.vue
  app/frontend/src/views/Admin.vue
  app/frontend/tests/unit/components/admin/ApiTester.spec.js
  app/frontend/tests/unit/components/admin/Clients.spec.js
  app/frontend/tests/unit/components/admin/HealthDialog.spec.js
  app/frontend/tests/unit/components/admin/JWTDialog.spec.js
  app/frontend/tests/unit/views/Admin.spec.js
  app/migrate-seed.js
  app/nodemon.json
  app/package.json
  app/src/seeders/20200330000000-dev-users.js
  openshift/README.md
  openshift/app.dc.yaml
  openshift/commonPipeline.groovy
Labels: bug, dependencies, enhancement

#160 Acronyms/users endpoint (spec approval)
  app/src/docs/v1.api-spec.yaml
Labels: documentation

#163 API for acronym user fetch
  app/src/components/acronyms.js
  app/src/components/keyCloakServiceClientMgr.js
  app/src/components/realmAdminSvc.js
  app/src/components/users.js
  app/src/routes/v1/acronyms.js
  app/src/services/acronym.js
  app/tests/unit/components/acronyms.spec.js
  app/tests/unit/components/fixtures/acronymUsers.json
  app/tests/unit/components/fixtures/keycloakUsers.json
  app/tests/unit/components/keyCloakServiceClientMgr.spec.js
  app/tests/unit/components/realmAdminSvc.spec.js
Labels: enhancement

#161 Update various styles to better align with BCGov Design
  app/frontend/src/assets/scss/style.scss
  app/frontend/src/components/RequestForm.vue
  app/frontend/src/components/Welcome.vue
  app/frontend/src/components/admin/ApiTester.vue
  app/frontend/src/components/admin/HealthDialog.vue
  app/frontend/src/components/admin/JWTDialog.vue
  app/frontend/src/components/apiAccess/Step1.vue
  app/frontend/src/components/apiAccess/Step2.vue
  app/frontend/src/components/apiAccess/Step3.vue
  app/frontend/src/components/apiAccess/Step4.vue
  app/frontend/src/components/base/BaseActionCard.vue
  app/frontend/src/components/base/BaseAuthButton.vue
  app/frontend/src/components/base/BaseDialog.vue
  app/frontend/src/components/base/BaseSecure.vue
  app/frontend/src/components/bcgov/BCGovFooter.vue
  app/frontend/src/components/bcgov/BCGovNavBar.vue
  app/frontend/src/views/Admin.vue
  app/frontend/src/views/NotFound.vue
  app/frontend/src/views/RequestAccount.vue
  app/frontend/tests/unit/components/RequestForm.spec.js
  app/frontend/tests/unit/components/base/BaseAuthButton.spec.js
  app/frontend/tests/unit/components/base/BaseSecure.spec.js
  app/frontend/tests/unit/views/RequestAccount.spec.js
  frontend/src/components/ApiCheck.vue
  frontend/src/components/Dialog.vue
  frontend/src/components/RegistrationForm.vue
Labels: bug, enhancement

#164 Team tab table
  app/frontend/src/components/Team.vue
  app/frontend/src/services/acronymService.js
  app/frontend/src/views/Application.vue
  app/frontend/tests/unit/components/Team.spec.js
  app/frontend/tests/unit/services/acronymService.spec.js
  app/frontend/tests/unit/services/fixtures/acronymUsers.json
  frontend/package.json
Labels: dependencies, enhancement

#166 Reduce memory pressure on Jest tests and pipeline fixes
  Jenkinsfile
  Jenkinsfile.cicd
  app/frontend/package.json
  app/package.json
  openshift/commonPipeline.groovy
Labels: bug

#168 Fix incorrect image references for SonarQube badges
  README.md
Labels: bug, documentation

#167 Client status/buttons wording changes
  app/frontend/package-lock.json
  app/frontend/package.json
  app/frontend/src/components/ApplicationList.vue
  app/frontend/src/components/apiAccess/ClientStatus.vue
  app/frontend/src/components/apiAccess/Step1.vue
  app/frontend/src/utils/constants.js
  app/frontend/src/utils/util.js
  app/frontend/tests/unit/components/apiAccess/ClientStatus.spec.js
Labels: dependencies, enhancement

#170 PW should reset for existing clients
  app/frontend/src/components/Team.vue
  app/src/components/keyCloakServiceClientMgr.js
  app/src/components/realmAdminSvc.js
  app/tests/unit/components/keyCloakServiceClientMgr.spec.js
  app/tests/unit/components/realmAdminSvc.spec.js
Labels: bug

#169 Admin stats
  app/frontend/src/components/admin/Clients.vue
  app/frontend/src/components/admin/ServiceClients.vue
  app/frontend/src/services/acronymService.js
  app/frontend/src/services/keycloakService.js
  app/frontend/src/views/Admin.vue
  app/frontend/tests/unit/components/admin/Clients.spec.js
  app/src/components/clients.js
  app/src/routes/v1/keycloak.js
  app/src/services/lifecycle.js
Labels: enhancement

#172 WebADE backend migrated to new app
  app/package-lock.json
  app/package.json
  app/src/components/permissionHelpers.js
  app/src/components/utils.js
  app/src/components/webade.js
  app/src/docs/v1.api-spec.yaml
  app/src/routes/v1.js
  app/src/routes/v1/acronyms.js
  app/src/routes/v1/webade.js
  app/src/seeders/20200330000000-dev-users.js
  app/tests/common/helper.js
  app/tests/unit/components/fixtures/configForm.json
  app/tests/unit/components/fixtures/token.json
  app/tests/unit/components/fixtures/webadeList.json
  app/tests/unit/components/fixtures/webadeListWithInsecurePrefs.json
  app/tests/unit/components/utils.spec.js
  app/tests/unit/components/webade.spec.js
  app/tests/unit/routes/fixtures/kauth.json
  app/tests/unit/routes/v1.spec.js
  app/tests/unit/routes/v1/acronyms.spec.js
  app/tests/unit/routes/v1/webade.spec.js
  backend/tests/unit/components/fixtures/webadeList.json
Labels: dependencies, enhancement

#173 Fix bug causing API Access tab actions to fail to load
  app/src/routes/v1/acronyms.js
Labels: bug
