Repository bcgov/nr-get-token, pull requests merged in 2020-01, with the labels that each got.

#95 Add custom Network Security Policies
  Jenkinsfile
  Jenkinsfile.cicd
  openshift/backend.dc.yaml
  openshift/frontend-static.dc.yaml
  openshift/patroni-ephemeral.dc.yaml
  openshift/patroni.dc.yaml
Labels: enhancement

#96 Increase resource limits for frontend buildconfig
  openshift/frontend.bc.yaml
Labels: bug

#99 More webade restriction, some fixes, some unit tests
  backend/src/components/appConfig.js
  backend/src/components/auth.js
  backend/src/components/permissionHelpers.js
  backend/src/components/utils.js
  backend/src/docs/v1.api-spec.yaml
  backend/src/routes/v1/acronyms.js
  backend/src/routes/v1/webAde.js
  backend/tests/unit/components/acronyms.spec.js
  backend/tests/unit/components/appConfig.spec.js
  backend/tests/unit/components/fixtures/acronymDetail.json
  backend/tests/unit/components/fixtures/configForm.json
  backend/tests/unit/components/permissionHelpers.spec.js
  backend/tests/unit/components/utils.spec.js
  frontend/src/common/apiService.js
  frontend/src/components/ConfigForm.vue
  frontend/src/store/modules/auth.js
  frontend/src/store/modules/configForm.js
Labels: bug, enhancement

#102 Modify Acronym selection to be in Step 1
  backend/tests/unit/components/appConfig.spec.js
  frontend/src/common/apiService.js
  frontend/src/components/ConfigForm.vue
  frontend/src/store/modules/configForm.js
  frontend/src/utils/constants.js
  frontend/tests/unit/store/modules/configForm.actions.spec.js
  openshift/README.md
Labels: enhancement
