Repository bcgov/nr-get-token, pull requests merged in 2020-03, with the labels that each got.

#128 Minor Jenkins Pipeline Refactor
  Jenkinsfile
  Jenkinsfile.cicd
  openshift/commonPipeline.groovy
  openshift/patroni-ephemeral.dc.yaml
Labels: bug, enhancement

#130 Add Vuex to Frontend and minor bugfixes
  Jenkinsfile
  app/frontend/package-lock.json
  app/frontend/package.json
  app/frontend/src/components/base/BaseAuthButton.vue
  app/frontend/src/components/bcgov/BCGovNavBar.vue
  app/frontend/src/main.js
  app/frontend/src/router/index.js
  app/frontend/src/store/index.js
Labels: bug, enhancement

#129 My Applications page
  app/frontend/src/components/ApplicationList.vue
  app/frontend/src/components/base/BaseActionCard.vue
  app/frontend/src/components/bcgov/BCGovNavBar.vue
  app/frontend/src/router/index.js
  app/frontend/src/views/Application.vue
  app/frontend/src/views/MyApps.vue
Labels: enhancement

#126 Refactor homepage
  app/frontend/.env
  app/frontend/.env.development
  app/frontend/.env.test
  app/frontend/src/components/Welcome.vue
  app/frontend/src/components/bcgov/BCGovNavBar.vue
  app/frontend/src/router/index.js
  app/frontend/src/utils/commonServices.js
  app/frontend/src/views/About.vue
  app/frontend/src/views/Home.vue
  app/frontend/tests/unit/components/Welcome.spec.js
  app/frontend/tests/unit/components/bcgov/BCGovNavBar.spec.js
  app/frontend/tests/unit/views/About.spec.js
Labels: enhancement

#131 Restore DB connectivity in backend app
  app/.sequelizerc
  app/app.js
  app/jest.config.js
  app/lcov-fix.js
  app/package-lock.json
  app/package.json
  app/src/migrations/20190729000000-initialize-database.js
  app/src/migrations/20200107052720-add-acronym-webade-flag-columns.js
  app/src/migrations/20200123221832-add-acronym-description.js
  app/src/models/acronym.js
  app/src/models/index.js
  app/src/models/lifecycle.js
  app/src/models/lifecyclehistory.js
  app/src/models/user.js
  app/src/models/useracronym.js
  app/src/services/acronym.js
  app/src/services/audit.js
  app/src/services/index.js
  app/src/services/lifecycle.js
  app/src/services/user.js
  openshift/app.bc.yaml
  openshift/app.dc.yaml
Labels: dependencies, enhancement

#132 Ui for application cards
  app/frontend/src/components/ApplicationList.vue
  app/frontend/src/components/base/BaseActionCard.vue
Labels: enhancement

#133 Add API spec proposal for user acronym get and delete actions
  README.md
  app/README.md
  app/app.js
  app/frontend/README.md
  app/frontend/public/favicon.ico
  app/package-lock.json
  app/package.json
  app/src/docs/docs.js
  app/src/docs/v1.api-spec.yaml
  app/src/routes/v1.js
  app/tests/unit/routes/v1.spec.js
  openshift/README.md
Labels: documentation, enhancement

#134 Set up calling acronym data from store. Add unit tests
  app/frontend/src/components/ApplicationList.vue
  app/frontend/src/services/userService.js
  app/frontend/src/store/index.js
  app/frontend/src/store/modules/user.js
  app/frontend/tests/unit/components/ApplicationList.spec.js
  app/frontend/tests/unit/services/userService.spec.js
  app/frontend/tests/unit/store/index.spec.js
  app/frontend/tests/unit/store/modules/user.actions.spec.js
  app/frontend/tests/unit/store/modules/user.spec.js
  app/frontend/tests/unit/views/Application.spec.js
  app/frontend/tests/unit/views/MyApps.spec.js
Labels: enhancement

#135 Implement getUserAcronym Endpoint
  app/frontend/src/components/base/BaseAuthButton.vue
  app/frontend/src/router/index.js
  app/package-lock.json
  app/package.json
  app/src/components/users.js
  app/src/docs/v1.api-spec.yaml
  app/src/routes/v1.js
  app/src/routes/v1/users.js
  app/src/services/user.js
  app/tests/unit/components/users.spec.js
  app/tests/unit/routes/v1.spec.js
  app/tests/unit/routes/v1/users.spec.js
Labels: enhancement

#137 Implement Frontend Service Layer structure
  app/frontend/package-lock.json
  app/frontend/package.json
  app/frontend/src/components/HelloCall.vue
  app/frontend/src/main.js
  app/frontend/src/services/helloService.js
  app/frontend/src/services/index.js
  app/frontend/src/services/interceptors.js
  app/frontend/src/services/userService.js
  app/frontend/src/store/modules/user.js
  app/frontend/tests/unit/services/helloService.spec.js
  app/frontend/tests/unit/services/userService.spec.js
  app/frontend/tests/unit/store/modules/user.actions.spec.js
Labels: dependencies, enhancement

#139 Request Account form - basic setup
  app/frontend/src/assets/scss/style.scss
  app/frontend/src/components/ApplicationList.vue
  app/frontend/src/components/RequestForm.vue
  app/frontend/src/components/Welcome.vue
  app/frontend/src/components/base/BaseDialog.vue
  app/frontend/src/components/bcgov/BCGovFooter.vue
  app/frontend/src/components/bcgov/BCGovNavBar.vue
  app/frontend/src/main.js
  app/frontend/src/router/index.js
  app/frontend/src/utils/constants.js
  app/frontend/src/views/RequestAccount.vue
Labels: enhancement

#141 Reimplement /email endpoint in GETOK backend
  Jenkinsfile
  app/config/custom-environment-variables.json
  app/config/default.json
  app/config/test.json
  app/package-lock.json
  app/package.json
  app/src/components/email.js
  app/src/components/utils.js
  app/src/docs/v1.api-spec.yaml
  app/src/routes/v1.js
  app/src/routes/v1/email.js
  app/src/routes/v1/users.js
  app/tests/unit/components/email.spec.js
  app/tests/unit/components/utils.spec.js
  app/tests/unit/routes/v1/email.spec.js
  app/tests/unit/routes/v1/hello.spec.js
  openshift/README.md
  openshift/app.dc.yaml
Labels: dependencies, documentation, enhancement

#143 Connect Request Account page with /email endpoint
  app/frontend/src/components/HelloCall.vue
  app/frontend/src/components/HelloWorld.vue
  app/frontend/src/components/RequestForm.vue
  app/frontend/src/components/bcgov/BCGovNavBar.vue
  app/frontend/src/router/index.js
  app/frontend/src/services/emailService.js
  app/frontend/src/services/helloService.js
  app/frontend/src/services/index.js
  app/frontend/src/services/userService.js
  app/frontend/src/views/RequestAccount.vue
  app/frontend/tests/unit/components/HelloCall.spec.js
  app/frontend/tests/unit/components/HelloWorld.spec.js
  app/frontend/tests/unit/components/bcgov/BCGovNavBar.spec.js
  app/frontend/tests/unit/services/emailService.spec.js
  app/frontend/tests/unit/services/helloService.spec.js
  app/frontend/tests/unit/services/userService.spec.js
  app/frontend/tests/unit/views/RequestAccount.spec.js
  app/src/components/hello.js
  app/src/routes/v1.js
  app/src/routes/v1/hello.js
  app/tests/unit/components/hello.spec.js
  app/tests/unit/routes/v1/hello.spec.js
Labels: enhancement

#144 Bc fonts
  app/frontend/package-lock.json
  app/frontend/package.json
  app/frontend/src/assets/scss/style.scss
  app/frontend/src/main.js
Labels: dependencies, ui

#142 Display service client status (with dummy data)
  app/frontend/src/components/ApplicationList.vue
  app/frontend/src/services/userService.js
  app/frontend/src/store/modules/user.js
  app/src/components/users.js
  app/src/docs/v1.api-spec.yaml
  app/src/routes/v1/users.js
Labels: enhancement

#146 Abstract Keycloak behind Vuex module layer
  app/frontend/src/components/ApplicationList.vue
  app/frontend/src/components/base/BaseAuthButton.vue
  app/frontend/src/components/base/BaseSecure.vue
  app/frontend/src/main.js
  app/frontend/src/store/index.js
  app/frontend/src/store/modules/auth.js
  app/frontend/src/store/modules/user.js
  app/frontend/src/views/MyApps.vue
  app/frontend/src/views/Secure.vue
  app/frontend/tests/unit/components/ApplicationList.spec.js
  app/frontend/tests/unit/components/base/BaseAuthButton.spec.js
  app/frontend/tests/unit/components/base/BaseSecure.spec.js
  app/frontend/tests/unit/store/modules/auth.getters.spec.js
  app/frontend/tests/unit/store/modules/user.actions.spec.js
  app/frontend/tests/unit/store/modules/user.getters.spec.js
  app/frontend/tests/unit/store/modules/user.mutations.spec.js
  app/frontend/tests/unit/store/modules/user.spec.js
  app/frontend/tests/unit/views/MyApps.spec.js
Labels: enhancement

#147 Refactor requestForm to use auth store and Documentation
  app/frontend/README.md
  app/frontend/src/assets/scss/style.scss
  app/frontend/src/components/RequestForm.vue
  app/frontend/src/components/base/BaseAuthButton.vue
  app/frontend/tests/unit/App.spec.js
  app/frontend/tests/unit/components/RequestForm.spec.js
Labels: documentation, enhancement

#150 Add secure admin page support
  app/frontend/src/components/base/BaseSecure.vue
  app/frontend/src/components/bcgov/BCGovNavBar.vue
  app/frontend/src/router/index.js
  app/frontend/src/store/modules/auth.js
  app/frontend/src/utils/constants.js
  app/frontend/src/views/Admin.vue
  app/frontend/src/views/NotFound.vue
  app/frontend/tests/unit/components/base/BaseSecure.spec.js
  app/frontend/tests/unit/components/bcgov/BCGovNavBar.spec.js
  app/frontend/tests/unit/store/modules/auth.getters.spec.js
Labels: bug, enhancement

#151 Add JWT Token support to admin page
  app/frontend/src/components/JWTDialog.vue
  app/frontend/src/components/RequestForm.vue
  app/frontend/src/components/base/BaseDialog.vue
  app/frontend/src/store/modules/auth.js
  app/frontend/src/views/Admin.vue
  app/frontend/tests/unit/components/JWTDialog.spec.js
  app/frontend/tests/unit/components/RequestForm.spec.js
  app/frontend/tests/unit/components/base/BaseDialog.spec.js
  app/frontend/tests/unit/store/modules/auth.getters.spec.js
  app/frontend/tests/unit/views/Admin.spec.js
Labels: bug, enhancement

#152 Add ApiTester and HealthCheck feature
  app/frontend/src/components/ApiTester.vue
  app/frontend/src/components/HealthDialog.vue
  app/frontend/src/components/JWTDialog.vue
  app/frontend/src/services/emailService.js
  app/frontend/src/services/healthService.js
  app/frontend/src/services/testerService.js
  app/frontend/src/services/userService.js
  app/frontend/src/utils/constants.js
  app/frontend/src/views/Admin.vue
  app/frontend/tests/unit/components/ApiTester.spec.js
  app/frontend/tests/unit/components/HealthDialog.spec.js
  app/frontend/tests/unit/components/JWTDialog.spec.js
  app/frontend/tests/unit/services/emailService.spec.js
  app/frontend/tests/unit/services/healthService.spec.js
  app/frontend/tests/unit/services/testerService.spec.js
  app/frontend/tests/unit/services/userService.spec.js
  app/frontend/tests/unit/views/Admin.spec.js
  app/frontend/tests/unit/views/Application.spec.js
  app/jest.config.js
  app/package-lock.json
  app/package.json
  app/src/components/checks.js
  app/src/components/email.js
  app/src/components/keyCloakServiceClientMgr.js
  app/src/components/realmAdminSvc.js
  app/src/components/utils.js
  app/src/docs/v1.api-spec.yaml
  app/src/routes/v1.js
  app/src/routes/v1/checks.js
  app/tests/unit/components/checks.spec.js
  app/tests/unit/components/keyCloakServiceClientMgr.spec.js
  app/tests/unit/components/realmAdminSvc.spec.js
  app/tests/unit/components/utils.spec.js
  app/tests/unit/routes/v1/checks.spec.js
  app/tests/unit/routes/v1/users.spec.js
  openshift/README.md
  openshift/app.dc.yaml
  openshift/commonPipeline.groovy
Labels: bug, dependencies, enhancement

#154 Hard update package dependencies on app and frontend
  app/frontend/package-lock.json
  app/frontend/package.json
  app/frontend/src/components/JWTDialog.vue
  app/frontend/tests/unit/components/JWTDialog.spec.js
  app/package-lock.json
  app/package.json
Labels: bug, dependencies

#155 Step 1 to Step 2
  app/frontend/src/components/ApplicationList.vue
  app/frontend/src/components/apiAccess/ApiAccess.vue
  app/frontend/src/components/apiAccess/Step1.vue
  app/frontend/src/components/apiAccess/Step2.vue
  app/frontend/src/components/base/BaseDialog.vue
  app/frontend/src/services/acronymService.js
  app/frontend/src/store/index.js
  app/frontend/src/store/modules/apiAccess.js
  app/frontend/src/utils/constants.js
  app/frontend/src/utils/util.js
  app/frontend/src/views/Application.vue
  app/frontend/tests/unit/views/Application.spec.js
  app/src/components/acronyms.js
  app/src/components/users.js
  app/src/components/utils.js
  app/src/routes/v1.js
  app/src/routes/v1/acronyms.js
  app/tests/unit/components/acronyms.spec.js
  app/tests/unit/components/users.spec.js
  frontend/src/utils/constants.js
  openshift/README.md
  openshift/app.dc.yaml
  openshift/commonPipeline.groovy
Labels: enhancement

#149 Onboarding Stats for Admin page
  app/frontend/src/components/Clients.vue
  app/frontend/src/services/keycloakService.js
  app/frontend/src/views/Admin.vue
  app/frontend/tests/unit/components/Clients.spec.js
  app/src/components/clients.js
  app/src/components/keyCloakServiceClientMgr.js
  app/src/docs/v1.api-spec.yaml
  app/src/routes/v1.js
  app/src/routes/v1/keycloak.js
Labels: enhancement

#157 Step 3 of API Access
  app/frontend/package-lock.json
  app/frontend/package.json
  app/frontend/src/assets/scss/style.scss
  app/frontend/src/components/apiAccess/ApiAccess.vue
  app/frontend/src/components/apiAccess/Step2.vue
  app/frontend/src/components/apiAccess/Step3.vue
  app/frontend/src/services/acronymService.js
  app/frontend/src/services/keycloakService.js
  app/frontend/src/store/modules/apiAccess.js
  app/frontend/src/utils/constants.js
  app/package-lock.json
  app/package.json
  app/src/components/acronyms.js
  app/src/components/permissionHelpers.js
  app/src/routes/v1/acronyms.js
  app/src/routes/v1/keycloak.js
  app/tests/unit/components/acronyms.spec.js
  app/tests/unit/components/fixtures/acronymDetail.json
  app/tests/unit/components/permissionHelpers.spec.js
  backend/src/routes/v1/acronyms.js
Labels: dependencies, enhancement
