Repository bcgov/nr-get-token, pull requests merged in 2020-02, with the labels that each got.

#108 GETOK login ui change from UX feedback
  README.md
  backend/README.md
  backend/package.json
  docs/developer-guide.md
  frontend/.env
  frontend/.env.development
  frontend/.env.test
  frontend/README.md
  frontend/package.json
  frontend/public/index.html
  frontend/src/components/Footer.vue
  frontend/src/components/Header.vue
  frontend/src/components/Home.vue
  frontend/tests/unit/components/Home.spec.js
  frontend/tests/unit/components/WebAdeVisualizer/SecurityUtils.spec.js
  openshift/README.md
  package-lock.json
Labels: enhancement, ui

#111 Feature/client status
  backend/app.js
  backend/config/default.json
  backend/src/components/keyCloakServiceClientMgr.js
  backend/src/components/realmAdminSvc.js
  backend/src/docs/v1.api-spec.yaml
  backend/src/models/lifecycle.js
  backend/src/models/lifecyclehistory.js
  backend/src/routes/v1/keyCloak.js
  backend/src/services/lifecycle.js
  backend/tests/unit/components/keyCloakServiceClientMgr.spec.js
  backend/tests/unit/components/realmAdminSvc.spec.js
  frontend/src/components/webAdeVisualizer/SecurityUtils.vue
Labels: enhancement

#115 Hard refresh npm dependencies
  .gitignore
  backend/config/test.json
  backend/package-lock.json
  backend/tests/unit/components/email.spec.js
  frontend/package-lock.json
  frontend/package.json
  frontend/tests/unit/common/apiService.spec.js
  package-lock.json
Labels: enhancement

#117 Refactor backend to check user acronym permissions from DB
  backend/app.js
  backend/config/database.js
  backend/package-lock.json
  backend/package.json
  backend/src/components/acronyms.js
  backend/src/components/appConfig.js
  backend/src/components/audit.js
  backend/src/components/auth.js
  backend/src/components/permissionHelpers.js
  backend/src/components/utils.js
  backend/src/routes/auth.js
  backend/src/routes/v1/acronyms.js
  backend/src/routes/v1/audit.js
  backend/src/routes/v1/keyCloak.js
  backend/src/routes/v1/webAde.js
  backend/src/services/user.js
  backend/tests/unit/components/appConfig.spec.js
  backend/tests/unit/components/keyCloakServiceClientMgr.spec.js
  backend/tests/unit/components/permissionHelpers.spec.js
  backend/tests/unit/components/utils.spec.js
  frontend/package-lock.json
  frontend/package.json
Labels: enhancement

#118 Update frontend to populate acronyms from /auth/token endpoint
  backend/src/components/auth.js
  frontend/src/App.vue
  frontend/src/common/apiService.js
  frontend/src/components/ConfigForm.vue
  frontend/src/router.js
  frontend/src/store/index.js
  frontend/src/store/modules/auth.js
Labels: bug, enhancement

#123 Change Patroni default storage class to netapp-block-standard
  frontend/Caddyfile
  openshift/patroni.dc.yaml
Labels: enhancement
